# Generated by Django 4.2.1 on 2023-08-10 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_photo', models.ImageField(blank=True, null=True, upload_to='image_user/', verbose_name=' фото геймера')),
                ('ratingUser', models.SmallIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='геймер')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Tn', 'Танки'), ('SM', 'Мастера заклинаний'), ('DD', 'ДД'), ('QG', 'Квестгиверы'), ('Hl', 'Хилы'), ('LW', 'Кожевники'), ('BS', 'Кузнецы'), ('DR', 'Торговцы'), ('GM', 'Гилдмастеры'), ('PM', 'Зельевары')], max_length=64, unique=True, verbose_name='категория')),
                ('dataCreation', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('dataUpdate', models.DateTimeField(auto_now=True, verbose_name='редактировано')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image_photo/')),
                ('rating', models.SmallIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanboard.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='текст комментария')),
                ('dataCreation', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('rating', models.SmallIntegerField(default=0)),
                ('approved_commit', models.BooleanField(blank=True, default=False, verbose_name='Комментарий одобрен')),
                ('commentPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanboard.post')),
                ('commentUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор комментария')),
            ],
        ),
    ]
