# Generated by Django 4.2.1 on 2023-08-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('QG', 'Квестгиверы'), ('LW', 'Кожевники'), ('Hl', 'Хилы'), ('DR', 'Торговцы'), ('DD', 'ДД'), ('Tn', 'Танки'), ('BS', 'Кузнецы'), ('GM', 'Гилдмастеры'), ('SM', 'Мастера заклинаний'), ('PM', 'Зельевары')], max_length=64, unique=True, verbose_name='категория'),
        ),
    ]
