# Generated by Django 4.2.1 on 2023-08-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanboard', '0002_alter_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approved_commit',
            new_name='approved_comment',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('DR', 'Торговцы'), ('PM', 'Зельевары'), ('Tn', 'Танки'), ('SM', 'Мастера заклинаний'), ('DD', 'ДД'), ('Hl', 'Хилы'), ('LW', 'Кожевники'), ('BS', 'Кузнецы'), ('GM', 'Гилдмастеры'), ('QG', 'Квестгиверы')], max_length=64, unique=True, verbose_name='категория'),
        ),
    ]
