# Generated by Django 4.2.1 on 2023-08-10 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanboard', '0003_rename_approved_commit_comment_approved_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file/', verbose_name='другое'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/', verbose_name='видео'),
        ),
        migrations.AddField(
            model_name='profile',
            name='site',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='веб-сайт'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vk',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='аккаунт VK'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanboard.profile', verbose_name='геймер'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('PM', 'Зельевары'), ('DR', 'Торговцы'), ('GM', 'Гилдмастеры'), ('DD', 'ДД'), ('Tn', 'Танки'), ('SM', 'Мастера заклинаний'), ('BS', 'Кузнецы'), ('LW', 'Кожевники'), ('Hl', 'Хилы'), ('QG', 'Квестгиверы')], max_length=64, unique=True, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image_photo/', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=128, verbose_name='название'),
        ),
    ]
