# Generated by Django 4.2.1 on 2023-08-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanboard', '0005_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('GM', 'Гилдмастеры'), ('Hl', 'Хилы'), ('BS', 'Кузнецы'), ('Tn', 'Танки'), ('DD', 'ДД'), ('LW', 'Кожевники'), ('QG', 'Квестгиверы'), ('DR', 'Торговцы'), ('PM', 'Зельевары'), ('SM', 'Мастера заклинаний')], max_length=64, verbose_name='категория'),
        ),
    ]
