# Generated by Django 4.2.1 on 2023-08-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanboard', '0006_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('BS', 'Кузнецы'), ('DD', 'ДД'), ('Hl', 'Хилы'), ('LW', 'Кожевники'), ('GM', 'Гилдмастеры'), ('DR', 'Торговцы'), ('QG', 'Квестгиверы'), ('Tn', 'Танки'), ('SM', 'Мастера заклинаний'), ('PM', 'Зельевары')], max_length=64, verbose_name='категория'),
        ),
    ]
