# Generated by Django 4.2.1 on 2023-08-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanboard', '0007_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Tn', 'Танки'), ('GM', 'Гилдмастеры'), ('DR', 'Торговцы'), ('BS', 'Кузнецы'), ('Hl', 'Хилы'), ('PM', 'Зельевары'), ('LW', 'Кожевники'), ('QG', 'Квестгиверы'), ('SM', 'Мастера заклинаний'), ('DD', 'ДД')], max_length=64, verbose_name='категория'),
        ),
    ]
