# Generated by Django 4.2.1 on 2023-08-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanboard', '0008_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('QG', 'Квестгиверы'), ('DR', 'Торговцы'), ('BS', 'Кузнецы'), ('SM', 'Мастера заклинаний'), ('Tn', 'Танки'), ('GM', 'Гилдмастеры'), ('PM', 'Зельевары'), ('Hl', 'Хилы'), ('DD', 'ДД'), ('LW', 'Кожевники')], max_length=64, verbose_name='категория'),
        ),
    ]
