# Generated by Django 4.2.1 on 2023-08-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanboard', '0009_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('PM', 'Зельевары'), ('BS', 'Кузнецы'), ('DD', 'ДД'), ('Tn', 'Танки'), ('Hl', 'Хилы'), ('QG', 'Квестгиверы'), ('DR', 'Торговцы'), ('SM', 'Мастера заклинаний'), ('LW', 'Кожевники'), ('GM', 'Гилдмастеры')], max_length=64, verbose_name='категория'),
        ),
    ]
