# Generated by Django 4.2.1 on 2023-08-30 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fanboard', '0010_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislike_post',
            field=models.ManyToManyField(blank=True, related_name='dislike_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='like_post',
            field=models.ManyToManyField(blank=True, related_name='like_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('BS', 'Кузнецы'), ('DD', 'ДД'), ('SM', 'Мастера заклинаний'), ('DR', 'Торговцы'), ('LW', 'Кожевники'), ('GM', 'Гилдмастеры'), ('Hl', 'Хилы'), ('QG', 'Квестгиверы'), ('PM', 'Зельевары'), ('Tn', 'Танки')], max_length=64, verbose_name='категория'),
        ),
    ]
