# Generated by Django 4.2.1 on 2023-09-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanboard', '0012_comment_dislike_com_comment_like_com_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved_comment',
            field=models.BooleanField(default=False, verbose_name='Комментарий одобрен'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('BS', 'Кузнецы'), ('Tn', 'Танки'), ('SM', 'Мастера заклинаний'), ('DD', 'ДД'), ('QG', 'Квестгиверы'), ('PM', 'Зельевары'), ('Hl', 'Хилы'), ('DR', 'Торговцы'), ('LW', 'Кожевники'), ('GM', 'Гилдмастеры')], max_length=64, verbose_name='категория'),
        ),
    ]
