# Generated by Django 4.2.1 on 2023-09-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanboard', '0013_alter_comment_approved_comment_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('BS', 'Кузнецы'), ('PM', 'Зельевары'), ('DR', 'Торговцы'), ('Hl', 'Хилы'), ('DD', 'ДД'), ('Tn', 'Танки'), ('GM', 'Гилдмастеры'), ('LW', 'Кожевники'), ('SM', 'Мастера заклинаний'), ('QG', 'Квестгиверы')], max_length=64, verbose_name='категория'),
        ),
    ]
