# Generated by Django 4.2.1 on 2023-09-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanboard', '0014_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('DD', 'ДД'), ('PM', 'Зельевары'), ('QG', 'Квестгиверы'), ('LW', 'Кожевники'), ('Tn', 'Танки'), ('GM', 'Гилдмастеры'), ('DR', 'Торговцы'), ('BS', 'Кузнецы'), ('Hl', 'Хилы'), ('SM', 'Мастера заклинаний')], max_length=64, verbose_name='категория'),
        ),
    ]
