# Generated by Django 4.2.6 on 2023-10-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanboard', '0016_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('PM', 'Зельевары'), ('Hl', 'Хилы'), ('DR', 'Торговцы'), ('DD', 'ДД'), ('SM', 'Мастера заклинаний'), ('BS', 'Кузнецы'), ('LW', 'Кожевники'), ('GM', 'Гилдмастеры'), ('QG', 'Квестгиверы'), ('Tn', 'Танки')], max_length=64, verbose_name='категория'),
        ),
    ]
